# This is a basic workflow to help you get started with Actions

name: Compile to WASM

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get wasmenv
        run: curl https://raw.githubusercontent.com/wasienv/wasienv/master/install.sh | sh
        
      - name: Install dependencies
        run: sudo apt install cmake build-essential clang-format libclang-11-dev

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p build
          wasimake cmake -B build
          cd build
          wasimake make
          cd ..
      
      - name: Upload wasm artifact
        uses: actions/upload-artifact@v3
        with:
          name: purple.asm
          path: build/purple.asm
          retention-days: 1
          
