name: Build and Publish Doxygen Documentation

on:
  push:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          working-directory: '.'
          doxyfile-path: 'Doxyfile'
      
      - name: Copy documentation to gh-pages branch
        uses: actions/upload-artifact@v3
        with:
          name: doc-files
          path: docs
          retention-days: 1
  copy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      
      - name: Download documentation files
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: .
      
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Charles Averill
          author_email: charlesaverill20@gmail.com
          message: "Latest docs - ${{ github.event.repository.updated_at}}"
          branch: gh-pages
          add: '[docs/*]'
