name: Run Language Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install tools
        run: sudo apt install cmake build-essential clang-format libclang-11-dev
        
      - name: Compile Purple Executable
        run: ./compile.sh
      
      - name: Upload Purple Executable
        uses: actions/upload-artifact@v3
        with:
          name: purple
          path: ./bin/purple
          retention-days: 1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2

      - name: Download Purple Executable
        uses: actions/download-artifact@v3
        with:
          name: purple
          path: ./bin/purple
      
      - name: Run Tests
        run: ./test.sh --no-compile
