name: Run Language Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy compile.sh
        uses: actions/upload-artifact@v3
        with:
          name: compile.sh
          path: ./compile.sh
          retention-days: 1
      
      - name: Copy test.sh
        uses: actions/upload-artifact@v3
        with:
          name: test.sh
          path: ./test.sh
          retention-days: 1
      
      - name: Install CMake and build-essential
        run: sudo apt install cmake build-essential clang-format
        
      - name: Compile Purple Executable
        run: ./compile.sh
  
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Run Tests
        run: ./test.sh
