name: Run Language Tests

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install tools
        run: sudo apt install cmake build-essential clang-format libclang-13-dev
        
      - name: Compile Purple Executable
        run: ./compile.sh
      
      - name: Run Tests
        run: ./test.sh --no-compile
